apollo:
  bootstrap:
    enabled: true
    namespaces: application,babyfs.db_instance,babyfs.redis-servers,babyfs.grpc

rpc:
  enabled: true
  application:
    id: demo-forward-service
  protocol:
    port: 10013
  registry:
    address: ${consul.registry.address}
