apollo:
  bootstrap:
    enabled: true
    namespaces: application,babyfs.db_instance,babyfs.redis-servers,babyfs.grpc

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:mybatis/mapper/extension/*.xml
  type-aliases-package: com.babyfs.servicetk.testservice.impl.entity

spring:
  application:
    name: babyfs-note-service
  cache:
    type: redis
  redis:
    host: 6607
    port: 8806
    password:
    timeout: 10s
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-wait:
        max-idle: 10
        min-idle: 0
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.10.11:3306/babyfs_v2?useUnicode=true&characterEncoding=utf-8
    userName: root
    password: babyfs@Mysql
    type: com.alibaba.druid.pool.DruidDataSource

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#server:
#  port: 9090

# 输出mybatis查询日志
#logging:
#  level:
#    com:
#      babyfs:
#        noteservice:
#          impl:
#            dao: debug

#dubbo provider 配置
rpc:
  enabled: true
  application:
    id: com.babyfs.testService2
    name: com.babyfs.testService2
  protocol:
    port: ${server.port}
  registry:
    address: ${consul.registry.address}
